icon_combat=py.image.load(path('combat.png'))
icon_combat=py.transform.scale(icon_combat,[90,90]).convert_alpha()
icon_pawn=py.image.load(path('pawn.png'))
icon_pawn=py.transform.scale(icon_pawn,[100,100]).convert_alpha()
icon_heart=py.image.load(path('heart.png'))
icon_heart=py.transform.scale(icon_heart,(50,50)).convert_alpha()
icon_inspect=py.image.load(path('inspect.png'))
icon_inspect=py.transform.scale(icon_inspect,(90,90)).convert_alpha()
icon_encounter=py.image.load(path('encounter.png'))
icon_encounter=py.transform.scale(icon_encounter,(85,85)).convert_alpha()
icon_market=py.image.load(path('market.png'))
icon_market=py.transform.scale(icon_market,(95,95)).convert_alpha()
icon_shelter=py.image.load(path('shelter.png'))
icon_shelter=py.transform.scale(icon_shelter,(90,90)).convert_alpha()
icon_boss=py.image.load(path('boss.png'))
icon_boss=py.transform.scale(icon_boss,(90,90)).convert_alpha()
icon_shield=py.image.load(path('shield.png'))
icon_shield=py.transform.scale(icon_shield,(30,30)).convert_alpha()

bg=py.image.load(path('bg.jpg'))
bg=py.transform.scale(bg,[1280,720]).convert_alpha()
bg2=py.image.load(path('bg2.jpg'))
bg2=py.transform.scale(bg2,[1280,720]).convert_alpha()
bg3=py.image.load(path('bg3.jpg'))
bg3=py.transform.scale(bg3,[1280,720]).convert_alpha()
bg4=py.image.load(path('bg4.jpg'))
bg4=py.transform.scale(bg4,[1280,720]).convert_alpha()

inspect_list=list(csv.reader(open(path('inspect.csv'))))
item_list=list(csv.reader(open(path('item.csv'))))
item_name=[item_list[i][2] for i in range(len(item_list))]
encounter_list=list(csv.reader(open(path('encounter.csv'))))

music_explore=py.mixer.Sound(path('explore.wav'))
music_combat=py.mixer.Sound(path('combat.wav'))
music_market=py.mixer.Sound(path('market.wav'))
music_encounter=py.mixer.Sound(path('encounter.wav'))
music_inspect=py.mixer.Sound(path('inspect.wav'))
music_main=py.mixer.Sound(path('main.wav'))
music_shelter=py.mixer.Sound(path('shelter.wav'))

hit_player=py.mixer.Sound(path('hit_player.wav'))
hit_enemy=py.mixer.Sound(path('hit_enemy.wav'))
hit_dodge=py.mixer.Sound(path('hit_dodge.wav'))

icon_up=py.image.load(path('arrow_up.png'))
icon_up=py.transform.scale(icon_up,(90,40)).convert_alpha()
icon_down=py.image.load(path('arrow_down.png'))
icon_down=py.transform.scale(icon_down,(90,40)).convert_alpha()
icon_right=py.image.load(path('arrow_right.png'))
icon_right=py.transform.scale(icon_right,(40,90)).convert_alpha()
icon_left=py.image.load(path('arrow_left.png'))
icon_left=py.transform.scale(icon_left,(40,90)).convert_alpha()

icon_up2=py.image.load(path('arrow_up2.png'))
icon_up2=py.transform.scale(icon_up2,(90,40)).convert_alpha()
icon_down2=py.image.load(path('arrow_down2.png'))
icon_down2=py.transform.scale(icon_down2,(90,40)).convert_alpha()
icon_right2=py.image.load(path('arrow_right2.png'))
icon_right2=py.transform.scale(icon_right2,(40,90)).convert_alpha()
icon_left2=py.image.load(path('arrow_left2.png'))
icon_left2=py.transform.scale(icon_left2,(40,90)).convert_alpha()

compass=py.image.load(path('compass.png'))
compass=py.transform.scale(compass,(400,400)).convert_alpha()
